# keploy-config.yaml
record:
  path: ""
  command: ""
  proxyport: 0
  containerName: ""
  networkName: ""
  delay: 5
  passThroughPorts: []
test:
  path: ""
  command: ""
  proxyport: 0
  containerName: ""
  networkName: ""
  testSets: []
  noise: |-
    {
      "global": {
        "body": {},
        "header": {}
      },
      "test-sets": {
        "test-set-0": {
          "body": {},
          "header": {}
        }
      } 
    }
  delay: 5
  apiTimeout: 5
  passThroughPorts: []