record:
    path: ""
    # mandatory
    command: ""
    proxyport: 0
    containerName: ""
    networkName: ""
    delay: 5
    passThroughPorts: []
test:
    path: ""
    # mandatory
    command: ""
    proxyport: 0
    containerName: ""
    networkName: ""
    tests: |-
        {
          "test-set-name": ["test-case-name"]
        }
    globalNoise: |-
        {
          "global": {
            "body": {},
            "header": {}
          },
          "test-sets": {
            "test-set-name": {
              "body": {},
              "header": {}
            }
          }
        }
    delay: 5
    apiTimeout: 5
    passThroughPorts: []
