name: get-binary
description: "Download build or latest Keploy and expose its absolute path"

inputs:
  src:
    required: true
    description: "build | latest"

outputs:
  path:
    description: "binary path"

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.src }}

    - shell: bash
      run: |
        ls -l
        chmod +x ${{ inputs.src }}
        echo "path=$PWD/${{ inputs.src }}" >> "$GITHUB_OUTPUT"
