name: pull-image
description: "Pull Image"
runs:
  using: composite
  steps:
    - name: Pull Image
      shell: bash
      run: |
        docker pull ttl.sh/keploy/keploy:1h
        docker tag ttl.sh/keploy/keploy:1h ghcr.io/keploy/keploy:v2-dev