name: Go

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    steps:
      - run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...

      - uses: codfish/semantic-release-action@v1
        with:
          dry_run: true
          additional_packages: |
            ['@semantic-release/exec']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

