name: Go

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...
      - uses: codfish/semantic-release-action@v1
        with:
          dry_run: true
          additional_packages: |
            ['@semantic-release/exec']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: uraimo/run-on-arch-action@v2
        with: 
          arch: armv7
          distro: ubuntu18.04
          shell: /bin/bash

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          
          install: |
            apt install golang-go
          run: | 
            go version
            ls 
          # go build -v ./...
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          architecture: arm64

      - name: Build
        run: go build -v ./...
      - uses: codfish/semantic-release-action@v1
        with:
          dry_run: true
          additional_packages: |
            ['@semantic-release/exec']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}