name: Golang(http) On Linux
on:
  pull_request:
    branches: [main]
jobs:
  prepare:
    uses: ./.github/workflows/prepare-binary.yml

  http_golang_linux:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        include:
          - job: record_latest_replay_build
            record_src: latest
            replay_src: build
          - job: record_build_replay_latest
            record_src: build
            replay_src: latest
          - job: record_build_replay_build
            record_src: build
            replay_src: build
    name: ${{ matrix.job }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: list directory
        run: |
          echo "Listing the current directory"
          tree ./.github

      - id: record
        uses: ./.github/actions/download-binary
        with:
          src: ${{ matrix.record_src }}

      - id: replay
        uses: ./.github/actions/download-binary
        with:
          src: ${{ matrix.replay_src }}

      - name: Checkout the samples-go repository
        uses: actions/checkout@v4
        with:
          repository: keploy/samples-go
          path: samples-go

      - name: echo record and replay binary
        run: |
          echo "Record binary path: ${{ steps.record.outputs.path }}"
          echo "Replay binary path: ${{ steps.replay.outputs.path }}"

      - name: Run go-http application
        env:
          RECORD_BIN: ${{ steps.record.outputs.path }}
          REPLAY_BIN: ${{ steps.replay.outputs.path }}
        run: |
          cd samples-go/http-pokeapi
          chmod +x ./../../.github/workflows/test_workflow_scripts/golang-http-linux.sh
          source ./../../.github/workflows/test_workflow_scripts/golang-http-linux.sh