name: Prepare Binary
on:
  pull_request:
    branches: [main]
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Keploy (PR)
        run: go build -race -tags=viper_bind_struct -o keploy
      - uses: actions/upload-artifact@v4
        with: { name: build, path: keploy }

      - name: Upload latest release
        run: |
          LATEST=$(curl -s https://api.github.com/repos/keploy/keploy/releases/latest | jq -r .tag_name)
          URL="https://github.com/keploy/keploy/releases/download/${LATEST}/keploy_linux_amd64.tar.gz"
          curl -L "$URL" -o keploy.tar.gz
          tar -xzf keploy.tar.gz
          chmod +x keploy
      - uses: actions/upload-artifact@v4
        with: { name: latest, path: keploy }
  call-workflows:
    needs: build-and-upload
    strategy:
      fail-fast: false
      matrix:
        workflow: 
          - ./.github/workflows/golang_linux.yml
          - ./.github/workflows/node_linux.yml
    uses: ${{ matrix.workflow }}
